version: "3.8"

services:
  db: 
    container_name: db_paul
    image: postgres:14.5
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
    volumes:
      - "./postDb:/var/lib/postgresql/data"
    
  app:
    container_name: app_paul
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    # command:
      # - docker rmi $(docker images -f "dangling=true" -q)
      # - bash 
      # - -c
      # - | 
        # /app/wait-for-it.sh db:5432 -t 10
        # npm run start:prod
